name: Test K3d GitHub Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-k3d-action:
    name: Test K3d Cluster Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and use local action
        id: k3d
        uses: ./k3d-github-action  # Uses the action from the repository root
        with:
          cluster-name: test-k3d-cluster
          k3s-version: latest
          ports: 8080:80
          agents: 1
          timeout: 3

      - name: Set KUBECONFIG environment variable
        run: |
          echo "KUBECONFIG=${{ steps.k3d.outputs.kubeconfig-path }}" >> $GITHUB_ENV

      - name: Verify kubeconfig exists
        run: |
          echo "Cluster name: ${{ steps.k3d.outputs.cluster-name }}"
          echo "Kubeconfig path: ${{ steps.k3d.outputs.kubeconfig-path }}"

          # Debug kubeconfig content
          echo "Kubeconfig content:"
          cat $KUBECONFIG || echo "Kubeconfig file not found!"

          # Debug k3d cluster
          k3d cluster list

      - name: Fix kubeconfig server address
        run: |
          # Get the container IP address
          SERVER_IP=$(docker inspect k3d-${{ steps.k3d.outputs.cluster-name }}-server-0 --format '{{.NetworkSettings.IPAddress}}')
          echo "Server IP: $SERVER_IP"

          # Update the kubeconfig to use the container IP
          kubectl config set-cluster k3d-${{ steps.k3d.outputs.cluster-name }} --server=https://$SERVER_IP:6443 --kubeconfig=$KUBECONFIG

          # Debug the updated config
          kubectl config view

      - name: Verify cluster access
        run: |
          # Try to connect to the cluster
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -A
